In [8]:
#This imports all of the NumPy modules into the current namespace
from numpy import *

In [9]:
#This creates a random "array" of size 4x4;
random.rand(4,4)

array([[0.89176792, 0.05397881, 0.85567667, 0.69474031],
       [0.95063622, 0.04869645, 0.15422801, 0.21874648],
       [0.43995211, 0.26979871, 0.35257831, 0.25277497],
       [0.21647454, 0.47221858, 0.28865197, 0.65430729]])

In [10]:
#convert an array to a matrix by calling the mat() function
randMat = mat(random.rand(4,4))

In [11]:
#The .I operator solves the inverse of a matrix
invRandMat = randMat.I
invRandMat

matrix([[-3.85697575, -1.13204357,  1.06504471,  2.19705864],
        [ 5.54346505,  1.33069414, -1.89259321, -1.42197885],
        [-4.33364295, -2.2129421 ,  3.15798806,  1.1013173 ],
        [ 3.0340885 ,  2.99081614, -2.07030905, -1.52178126]])

In [12]:
#You can also do matrix multiplication
myIdent = randMat*invRandMat
myIdent

matrix([[ 1.00000000e+00,  8.34602014e-17,  2.86124785e-16,
          1.90399535e-16],
        [ 3.47894287e-16,  1.00000000e+00,  3.48646648e-16,
          1.48386198e-16],
        [ 5.99589561e-17,  2.24140823e-16,  1.00000000e+00,
         -1.19833701e-16],
        [ 4.38569933e-16, -1.30795173e-16,  7.81871951e-17,
          1.00000000e+00]])

In [13]:
#This gives you just the identity matrix, a 4x4 matrix where all elements are zero except
#the diagonals, which are one. This isn’t exactly true. There are some very small elements left over in the array 
myIdent - eye(4)

matrix([[-6.66133815e-16,  8.34602014e-17,  2.86124785e-16,
          1.90399535e-16],
        [ 3.47894287e-16, -2.22044605e-16,  3.48646648e-16,
          1.48386198e-16],
        [ 5.99589561e-17,  2.24140823e-16,  2.22044605e-16,
         -1.19833701e-16],
        [ 4.38569933e-16, -1.30795173e-16,  7.81871951e-17,
          4.44089210e-16]])